version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - sandoche
  - Mrsirdev
  - facs95
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: "weekly"
    day: "monday"
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - sandoche
  - Mrsirdev
  - facs95