name: Tests
on:
  pull_request:
  push:
    branches:
      - main
      - production

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test
        run: |
          make test
        if: env.GIT_DIFF